### ISSUE TITLE
Better "seeding" of similar patients by matching the full HPO hierarchies of the reference patient's symptoms to the index

### ISSUE THREAD

**Issue by sdumitriu** [phenotips/patient-network#24]
After phenotips/phenotips#825 is implemented, the patient search and match scoring should be changed so that instead of searching for exact symptom matches, the partial hierarchies of the reference and indexed symptoms should be compared, and the score should reflect how close the two branches match.

**Comment by buske** [comment]
This is getting really rough. We have a cohort of mitochondrial patients not matching each other because of this issue.

**Comment by buske** [comment]
Here's another example:
This HCS patient only matches 1/8 other HCS patients because of seeding failure: https://phenomecentral.org/P0000276

**Comment by sdumitriu** [comment]
I'm not sure that's the reason... From the look of it, the patients should match, even with the current seeding mechanism.

**Comment by buske** [comment]
Ah, indeed. It looks like the match is happening one-way, so is actually a case of #55. I did run the re-indexing script, but that didn't find any patients that needed re-indexing.

**Comment by buske** [comment]
Replaced by: https://phenotips.atlassian.net/browse/PN-24
