### ISSUE TITLE
Top Exomiser results should be limited on view access (e.g. Public cases)

### ISSUE THREAD

**Issue by buske** [phenotips/patient-network#73]
Currently, top Exomiser results are visible to all users on Public cases. This is fine and probably great, but it should be somehow limited so the whole Exomiser-processed VCF file isn't publicly available for Public cases (right now, you can just set the maximum display to ~500 genes and get the whole file). A server-side imposed maximum of ~5-10 variants should be imposed in cases where the user only has view access level.

**Comment by mjshepherd** [comment]
Currently the UI uses a select input which allows all users to select values from 1 to 20. However a server-side limit is not imposed which, I agree, should be. Should users with edit rights be given the UI option to select any number of genes?

**Comment by mjshepherd** [comment]
OK now without edit access the maximum number of genes that can be displayed is 10. With edit access the maximum is 500. Let me know if thats alright or if you think it should be changed.

**Comment by buske** [comment]
That's alright! Thanks!
