### ISSUE TITLE
Show potential diagnoses for matchable patients

### ISSUE THREAD

**Issue by buske** [phenotips/patient-network#81]
"Potential diagnoses" should be shown for matchable patients, without additional consent necessary. For now, "Confirmed diagnoses" can also be entered and shown without additional consent, though at some point we might want to clarify this.

**Comment by allasm** [comment]
The Similarity widget has been updated to always display "potential diagnosis" as part of 0c6a24cae9be95946d3f296c9bb6e1a2b1e06958 (did not realize that update also covered this issue until now). The rest can be refined together with refinement in PhenoTips itself for the next milestone

**Comment by buske** [comment]
Closed as duplicate of PN-82
