### ISSUE TITLE
Manually entered variants don't show up in the matching results

### ISSUE THREAD

**Issue by veronikaslc** [phenotips/patient-network#87]
After gene sections will be unified by PR phenotips/phenotips#1742 the variant list of getTopVariants() should also include gene names from candidate variants that have been entered, with pathogenic status 3-5 (VUS or higher). Changes will have to be made to: https://github.com/phenotips/patient-network/blob/master/similarity-data-impl/src/main/java/org/phenotips/data/similarity/internal/DefaultPatientGenotype.java#L98-L122

**Comment by buske** [comment]
Replaced with https://phenotips.atlassian.net/browse/PN-88
